name: Build and Test

on:
  push:
    branches: ["*"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y cmake g++ ${{ github.ref == 'refs/heads/main' && 'gcovr' || '' }}

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        ${{ github.ref == 'refs/heads/main' && '-DENABLE_COVERAGE=ON' || '' }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j$(nproc)

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build/ --output-on-failure

    - name: Run gcovr
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir gcovr
        cd gcovr
        gcovr -r .. \
        --exclude ../thirdparty/ \
        --html-details coverage.html \
        --html-theme github.dark-green

    - name: Upload coverage report
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: gcovr/
